### ISSUE TITLE
Container image version tag

### ISSUE THREAD

**Issue by nmeisenzahl** [whiteducksoftware/azure-devops-trigger-pipelines-task#2]
We should find a solution to build/push container images with a version tag. Until now we only support latest. 
Maybe we can just use the commit hash as tag for dev builds and the "git tag" as tag for new versions.
What do you think @StiviiK? 
fyi @mjisaak @msuemmchen

**Comment by StiviiK** [comment]
>Maybe we can just use the commit hash as tag for dev builds and the "git tag" as tag for new versions.

IMO this would be the best solution, you can easily see which version belongs to which changes.
Other schemes would complicate things unnecessarily.

**Comment by nmeisenzahl** [comment]
There is also a new Docker build&push action -> https://www.docker.com/blog/first-docker-github-action-is-here/
